using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace LittleEmber.EditorTools
{
    /// <summary>
    /// M0 animator generation (design doc Part VIII): the hero ships pre-sliced
    /// as 5 colors x 16 anim groups x 4 directions, so clips and the controller
    /// are generated by script, never hand-clicked.
    ///
    /// Output:
    ///   Assets/Art/Animations/Hero/color_N/hero_[group]_[DIR].anim  (320 clips)
    ///   Assets/Art/Animations/Hero/Pip.controller                   (color_1 base)
    ///   Assets/Art/Animations/Hero/Pip_color_2..5.overrideController (cloak colors)
    ///
    /// Animator contract: float Speed (0..1) · int Orientation (0=up,2=left,4=down,6=right)
    ///   triggers Attack/Roll/Hit/Bow/Lift/Throw · bools Dead/Block/Carrying.
    /// </summary>
    public static class HeroAnimatorBuilder
    {
        const string HeroRoot = "Assets/Gif/Super_Retro_Collection/Resources/Hero/hero";
        const string OutRoot = "Assets/Art/Animations/Hero";
        const int ColorCount = 5;

        // orientation ints follow the pack convention (see CharacterAppearance.cs)
        static readonly (string dir, int orientation)[] Dirs =
        {
            ("UP", 0), ("LEFT", 2), ("RIGHT", 6), ("DOWN", 4),
        };

        class GroupSpec
        {
            public string name;
            public float fps;
            public bool loop;
            public string trigger;      // non-null → AnyState trigger set
            public bool directionless;  // true → single hero_[group].png sheet (spin/dead/death)
            public GroupSpec(string n, float f, bool l, string t = null, bool d = false)
            { name = n; fps = f; loop = l; trigger = t; directionless = d; }
        }

        static readonly GroupSpec[] Groups =
        {
            new GroupSpec("idle",         6f, true),
            new GroupSpec("walk",         8f, true),
            new GroupSpec("run",         10f, true),
            new GroupSpec("breath_idle",  6f, true),
            new GroupSpec("carry_idle",   6f, true),
            new GroupSpec("carry_run",   10f, true),
            new GroupSpec("shield_block", 6f, true),
            new GroupSpec("shield_walk",  8f, true),
            new GroupSpec("dead",         6f, true,  null,    true),
            new GroupSpec("attack",      14f, false, "Attack"),
            new GroupSpec("spin",        12f, false, "Roll",   true),
            new GroupSpec("hit",         12f, false, "Hit"),
            new GroupSpec("death",       10f, false, null,     true),
            new GroupSpec("bow",         12f, false, "Bow"),
            new GroupSpec("lift",        10f, false, "Lift"),
            new GroupSpec("throw",       12f, false, "Throw"),
        };

        [MenuItem("LittleEmber/M0/1 - Generate Hero Animations")]
        public static void Generate()
        {
            EnsureFolder("Assets/Art");
            EnsureFolder("Assets/Art/Animations");
            EnsureFolder(OutRoot);

            // ---- pass 1: clips for every color ------------------------------
            var clipsByColor = new Dictionary<int, Dictionary<string, AnimationClip>>();
            int clipCount = 0;
            for (int color = 1; color <= ColorCount; color++)
            {
                string colorOut = $"{OutRoot}/color_{color}";
                EnsureFolder(colorOut);
                var table = new Dictionary<string, AnimationClip>();

                foreach (var group in Groups)
                {
                    // directionless groups ship one sheet: hero_[group].png
                    var sheetJobs = group.directionless
                        ? new[] { ($"{HeroRoot}/color_{color}/{group.name}/hero_{group.name}.png", $"hero_{group.name}") }
                        : Dirs.Select(d => ($"{HeroRoot}/color_{color}/{group.name}/hero_{group.name}_{d.dir}.png", $"hero_{group.name}_{d.dir}")).ToArray();

                    foreach (var (pngPath, clipName) in sheetJobs)
                    {
                        if (!File.Exists(pngPath)) continue;

                        var sprites = AssetDatabase.LoadAllAssetsAtPath(pngPath)
                            .OfType<Sprite>()
                            .OrderBy(s => TrailingIndex(s.name))
                            .ToArray();
                        if (sprites.Length == 0)
                        {
                            Debug.LogWarning($"[HeroAnimatorBuilder] No sprites in {pngPath}");
                            continue;
                        }

                        var clip = BuildClip(clipName, sprites, group.fps, group.loop);
                        string clipPath = $"{colorOut}/{clipName}.anim";
                        var existing = AssetDatabase.LoadAssetAtPath<AnimationClip>(clipPath);
                        if (existing != null) AssetDatabase.DeleteAsset(clipPath);
                        AssetDatabase.CreateAsset(clip, clipPath);
                        table[clip.name] = clip;
                        clipCount++;
                    }
                }
                clipsByColor[color] = table;
            }
            Debug.Log($"[HeroAnimatorBuilder] {clipCount} clips generated.");

            // ---- pass 2: base controller on color_1 -------------------------
            var baseClips = clipsByColor[1];
            var controller = BuildController(baseClips);

            // ---- pass 3: override controllers for cloaks color_2..5 ---------
            for (int color = 2; color <= ColorCount; color++)
            {
                var oc = new AnimatorOverrideController(controller);
                var pairs = new List<KeyValuePair<AnimationClip, AnimationClip>>();
                foreach (var kv in baseClips)
                {
                    if (clipsByColor[color].TryGetValue(kv.Key, out var over) && over != null)
                        pairs.Add(new KeyValuePair<AnimationClip, AnimationClip>(kv.Value, over));
                }
                oc.ApplyOverrides(pairs);
                string ocPath = $"{OutRoot}/Pip_color_{color}.overrideController";
                var existing = AssetDatabase.LoadAssetAtPath<AnimatorOverrideController>(ocPath);
                if (existing != null) AssetDatabase.DeleteAsset(ocPath);
                AssetDatabase.CreateAsset(oc, ocPath);
            }

            AssetDatabase.SaveAssets();
            Debug.Log("[HeroAnimatorBuilder] Pip.controller + 4 color overrides generated.");
        }

        // ------------------------------------------------------------------ clips

        static AnimationClip BuildClip(string name, Sprite[] frames, float fps, bool loop)
        {
            var clip = new AnimationClip { name = name, frameRate = fps };
            var binding = EditorCurveBinding.PPtrCurve("", typeof(SpriteRenderer), "m_Sprite");
            var keys = new ObjectReferenceKeyframe[frames.Length];
            for (int i = 0; i < frames.Length; i++)
                keys[i] = new ObjectReferenceKeyframe { time = i / fps, value = frames[i] };
            AnimationUtility.SetObjectReferenceCurve(clip, binding, keys);

            var settings = AnimationUtility.GetAnimationClipSettings(clip);
            settings.loopTime = loop;
            settings.stopTime = frames.Length / fps; // let the last frame show a full frame
            AnimationUtility.SetAnimationClipSettings(clip, settings);
            return clip;
        }

        static int TrailingIndex(string spriteName)
        {
            int us = spriteName.LastIndexOf('_');
            return (us >= 0 && int.TryParse(spriteName.Substring(us + 1), out int n)) ? n : 0;
        }

        // ------------------------------------------------------------------ controller

        static AnimatorController BuildController(Dictionary<string, AnimationClip> clips)
        {
            string path = $"{OutRoot}/Pip.controller";
            if (AssetDatabase.LoadAssetAtPath<AnimatorController>(path) != null)
                AssetDatabase.DeleteAsset(path);
            var controller = AnimatorController.CreateAnimatorControllerAtPath(path);

            controller.AddParameter("Speed", AnimatorControllerParameterType.Float);
            controller.AddParameter("Orientation", AnimatorControllerParameterType.Int);
            foreach (var t in new[] { "Attack", "Roll", "Hit", "Bow", "Lift", "Throw" })
                controller.AddParameter(t, AnimatorControllerParameterType.Trigger);
            foreach (var b in new[] { "Dead", "Block", "Carrying" })
                controller.AddParameter(b, AnimatorControllerParameterType.Bool);

            var sm = controller.layers[0].stateMachine;
            var states = new Dictionary<string, AnimatorState>();

            int row = 0;
            foreach (var group in Groups)
            {
                if (group.directionless)
                {
                    if (clips.TryGetValue($"hero_{group.name}", out var dclip))
                    {
                        var st = sm.AddState($"hero_{group.name}", GridPos(row));
                        st.motion = dclip;
                        states[$"hero_{group.name}"] = st;
                    }
                    row++;
                    continue;
                }
                foreach (var (dir, _) in Dirs)
                {
                    string key = $"hero_{group.name}_{dir}";
                    if (!clips.TryGetValue(key, out var clip)) continue;
                    var st = sm.AddState(key, GridPos(row));
                    st.motion = clip;
                    states[key] = st;
                }
                row++;
            }

            if (!states.TryGetValue("hero_idle_DOWN", out var defaultState))
            {
                Debug.LogError("[HeroAnimatorBuilder] hero_idle_DOWN missing — check hero sheets.");
                return controller;
            }
            sm.defaultState = defaultState;

            // ---- locomotion mesh: idle / walk / run --------------------------
            const float stopBelow = 0.1f;
            const float runAbove = 0.85f;
            string[] loco = { "idle", "walk", "run" };

            foreach (var (dir, o) in Dirs)
            {
                string idle = $"hero_idle_{dir}", walk = $"hero_walk_{dir}", run = $"hero_run_{dir}";
                bool hasIdle = states.ContainsKey(idle), hasWalk = states.ContainsKey(walk), hasRun = states.ContainsKey(run);

                if (hasIdle && hasWalk)
                {
                    Trans(states[idle], states[walk], Greater("Speed", stopBelow));
                    Trans(states[walk], states[idle], Less("Speed", stopBelow));
                }
                if (hasWalk && hasRun)
                {
                    Trans(states[walk], states[run], Greater("Speed", runAbove));
                    Trans(states[run], states[walk], Less("Speed", runAbove));
                }
                if (hasIdle && hasRun)
                {
                    Trans(states[idle], states[run], Greater("Speed", runAbove));
                    Trans(states[run], states[idle], Less("Speed", stopBelow));
                }

                // same tier, direction change
                foreach (var tier in loco)
                {
                    string fromKey = $"hero_{tier}_{dir}";
                    if (!states.ContainsKey(fromKey)) continue;
                    foreach (var (dir2, o2) in Dirs)
                    {
                        if (dir2 == dir) continue;
                        string toKey = $"hero_{tier}_{dir2}";
                        if (!states.ContainsKey(toKey)) continue;
                        Trans(states[fromKey], states[toKey], EqualsO(o2));
                    }
                }

                // ---- carry variants ------------------------------------------
                string carryIdle = $"hero_carry_idle_{dir}", carryRun = $"hero_carry_run_{dir}";
                bool hasCarryIdle = states.ContainsKey(carryIdle), hasCarryRun = states.ContainsKey(carryRun);

                if (hasIdle && hasCarryIdle)
                {
                    Trans(states[idle], states[carryIdle], If("Carrying"));
                    Trans(states[carryIdle], states[idle], IfNot("Carrying"));
                }
                if (hasRun && hasCarryRun)
                {
                    Trans(states[run], states[carryRun], If("Carrying"));
                    Trans(states[carryRun], states[run], IfNot("Carrying"));
                }
                if (hasWalk && hasCarryRun)
                {
                    Trans(states[walk], states[carryRun], If("Carrying"));
                    Trans(states[carryRun], states[walk], IfNot("Carrying"));
                }
                if (hasCarryIdle && hasCarryRun)
                {
                    Trans(states[carryIdle], states[carryRun], Greater("Speed", stopBelow));
                    Trans(states[carryRun], states[carryIdle], Less("Speed", stopBelow));
                }
                foreach (var tier in new[] { "carry_idle", "carry_run" })
                {
                    string fromKey = $"hero_{tier}_{dir}";
                    if (!states.ContainsKey(fromKey)) continue;
                    foreach (var (dir2, o2) in Dirs)
                    {
                        if (dir2 == dir) continue;
                        string toKey = $"hero_{tier}_{dir2}";
                        if (!states.ContainsKey(toKey)) continue;
                        Trans(states[fromKey], states[toKey], EqualsO(o2));
                    }
                }

                // ---- shield block / walk --------------------------------------
                string sBlock = $"hero_shield_block_{dir}", sWalk = $"hero_shield_walk_{dir}";
                if (states.ContainsKey(sBlock))
                {
                    var enter = sm.AddAnyStateTransition(states[sBlock]);
                    enter.hasExitTime = false; enter.duration = 0f; enter.canTransitionToSelf = false;
                    enter.AddCondition(AnimatorConditionMode.If, 0, "Block");
                    enter.AddCondition(AnimatorConditionMode.Equals, o, "Orientation");
                    enter.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead");

                    var exit = states[sBlock].AddTransition(defaultState);
                    exit.hasExitTime = false; exit.duration = 0.05f;
                    exit.AddCondition(AnimatorConditionMode.IfNot, 0, "Block");

                    if (states.ContainsKey(sWalk))
                    {
                        Trans(states[sBlock], states[sWalk], Greater("Speed", stopBelow));
                        var back = states[sWalk].AddTransition(states[sBlock]);
                        back.hasExitTime = false; back.duration = 0f;
                        back.AddCondition(AnimatorConditionMode.Less, stopBelow, "Speed");
                        back.AddCondition(AnimatorConditionMode.Equals, o, "Orientation");

                        var exitW = states[sWalk].AddTransition(defaultState);
                        exitW.hasExitTime = false; exitW.duration = 0.05f;
                        exitW.AddCondition(AnimatorConditionMode.IfNot, 0, "Block");

                        foreach (var (dir2, o2) in Dirs)
                        {
                            if (dir2 == dir) continue;
                            string toKey = $"hero_shield_walk_{dir2}";
                            if (!states.ContainsKey(toKey)) continue;
                            Trans(states[sWalk], states[toKey], EqualsO(o2));
                        }
                    }
                }
            }

            // ---- trigger action sets ------------------------------------------
            foreach (var group in Groups)
            {
                if (group.trigger == null) continue;

                // directionless (hero_spin): one state, returns to the facing-direction idle
                if (group.directionless)
                {
                    if (!states.TryGetValue($"hero_{group.name}", out var single)) continue;
                    var enterSingle = sm.AddAnyStateTransition(single);
                    enterSingle.hasExitTime = false; enterSingle.duration = 0f; enterSingle.canTransitionToSelf = false;
                    enterSingle.AddCondition(AnimatorConditionMode.If, 0, group.trigger);
                    enterSingle.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead");
                    foreach (var (dirB, oB) in Dirs)
                    {
                        if (!states.TryGetValue($"hero_idle_{dirB}", out var idleB)) continue;
                        var back = single.AddTransition(idleB);
                        back.hasExitTime = true; back.exitTime = 0.92f; back.duration = 0.04f;
                        back.AddCondition(AnimatorConditionMode.Equals, oB, "Orientation");
                    }
                    continue;
                }

                foreach (var (dir, o) in Dirs)
                {
                    string key = $"hero_{group.name}_{dir}";
                    if (!states.TryGetValue(key, out var st)) continue;

                    var enter = sm.AddAnyStateTransition(st);
                    enter.hasExitTime = false; enter.duration = 0f;
                    enter.canTransitionToSelf = group.trigger == "Attack"; // combos retrigger attack
                    enter.AddCondition(AnimatorConditionMode.If, 0, group.trigger);
                    enter.AddCondition(AnimatorConditionMode.Equals, o, "Orientation");
                    enter.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead");

                    string idleKey = $"hero_idle_{dir}";
                    if (states.TryGetValue(idleKey, out var idleSt))
                    {
                        var back = st.AddTransition(idleSt);
                        back.hasExitTime = true; back.exitTime = 0.92f; back.duration = 0.04f;
                    }
                }
            }

            // ---- death ---------------------------------------------------------
            // directionless variant (pack ships single-sheet hero_death / hero_dead)
            if (states.TryGetValue("hero_death", out var deathAny))
            {
                var enter = sm.AddAnyStateTransition(deathAny);
                enter.hasExitTime = false; enter.duration = 0f; enter.canTransitionToSelf = false;
                enter.AddCondition(AnimatorConditionMode.If, 0, "Dead");
                if (states.TryGetValue("hero_dead", out var deadAny))
                {
                    var toDead = deathAny.AddTransition(deadAny);
                    toDead.hasExitTime = true; toDead.exitTime = 1f; toDead.duration = 0.1f;
                }
            }
            foreach (var (dir, o) in Dirs)
            {
                string deathKey = $"hero_death_{dir}", deadKey = $"hero_dead_{dir}";
                if (states.TryGetValue(deathKey, out var deathSt))
                {
                    var enter = sm.AddAnyStateTransition(deathSt);
                    enter.hasExitTime = false; enter.duration = 0f; enter.canTransitionToSelf = false;
                    enter.AddCondition(AnimatorConditionMode.If, 0, "Dead");
                    enter.AddCondition(AnimatorConditionMode.Equals, o, "Orientation");

                    if (states.TryGetValue(deadKey, out var deadSt))
                    {
                        var toDead = deathSt.AddTransition(deadSt);
                        toDead.hasExitTime = true; toDead.exitTime = 1f; toDead.duration = 0.1f;
                    }
                }
            }

            EditorUtility.SetDirty(controller);
            return controller;
        }

        static Vector2 GridPos(int row) => new Vector2(60 + (row % 4) * 300, 60 + (row / 4) * 120);

        static (AnimatorConditionMode mode, float threshold, string param) Greater(string p, float t) => (AnimatorConditionMode.Greater, t, p);
        static (AnimatorConditionMode mode, float threshold, string param) Less(string p, float t) => (AnimatorConditionMode.Less, t, p);
        static (AnimatorConditionMode mode, float threshold, string param) If(string p) => (AnimatorConditionMode.If, 0, p);
        static (AnimatorConditionMode mode, float threshold, string param) IfNot(string p) => (AnimatorConditionMode.IfNot, 0, p);
        static (AnimatorConditionMode mode, float threshold, string param) EqualsO(int o) => (AnimatorConditionMode.Equals, o, "Orientation");

        static void Trans(AnimatorState from, AnimatorState to,
                          (AnimatorConditionMode mode, float threshold, string param) cond)
        {
            var t = from.AddTransition(to);
            t.hasExitTime = false;
            t.duration = 0f;
            t.AddCondition(cond.mode, cond.threshold, cond.param);
        }

        static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            string parent = Path.GetDirectoryName(path).Replace('\\', '/');
            string leaf = Path.GetFileName(path);
            if (!AssetDatabase.IsValidFolder(parent)) EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, leaf);
        }
    }
}
