using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;

namespace LittleEmber.Rendering
{
    /// <summary>
    /// Self-installing post-processing. Scenes are generated by editor builders and
    /// can't be re-baked from source control, so this builds a global URP Volume at
    /// runtime (bloom, vignette, tone mapping, warm color grade) and flips on the
    /// camera's renderPostProcessing flag. Tunings are per scene name.
    /// </summary>
    public static class RenderPolish
    {
        const string VolumeName = "URP_Polish";

        struct Tuning
        {
            public float bloomIntensity, bloomThreshold, vignette, exposure, saturation, contrast, temperature;
        }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        static void ResetStatics()
        {
            // safe under Enter-Play-Mode-without-domain-reload: never double-subscribe
            SceneManager.sceneLoaded -= OnSceneLoaded;
        }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        static void Install()
        {
            SceneManager.sceneLoaded += OnSceneLoaded;
            Apply(SceneManager.GetActiveScene().name);
        }

        static void OnSceneLoaded(Scene scene, LoadSceneMode mode) => Apply(scene.name);

        static void Apply(string sceneName)
        {
            var cam = Camera.main;
            if (cam != null)
            {
                var data = cam.GetUniversalAdditionalCameraData();
                if (data != null) data.renderPostProcessing = true;
            }

            var volume = FindVolume();
            var profile = volume.profile;
            if (profile == null || profile.name != VolumeName)
            {
                profile = ScriptableObject.CreateInstance<VolumeProfile>();
                profile.name = VolumeName;
                volume.profile = profile;
            }
            else
            {
                foreach (var c in profile.components) Object.Destroy(c);
                profile.components.Clear();
            }

            var t = TuningFor(sceneName);

            var bloom = profile.Add<Bloom>();
            bloom.threshold.Override(t.bloomThreshold);
            bloom.intensity.Override(t.bloomIntensity);
            bloom.scatter.Override(0.7f);

            var vig = profile.Add<Vignette>();
            vig.intensity.Override(t.vignette);
            vig.smoothness.Override(0.55f);

            var color = profile.Add<ColorAdjustments>();
            color.postExposure.Override(t.exposure);
            color.saturation.Override(t.saturation);
            color.contrast.Override(t.contrast);

            var wb = profile.Add<WhiteBalance>();
            wb.temperature.Override(t.temperature);

            var tone = profile.Add<Tonemapping>();
            tone.mode.Override(TonemappingMode.Neutral);

            volume.isGlobal = true;
            volume.priority = 10f;
        }

        static Volume FindVolume()
        {
            var existing = Object.FindObjectsByType<Volume>(FindObjectsSortMode.None);
            for (int i = 0; i < existing.Length; i++)
                if (existing[i] != null && existing[i].isGlobal && existing[i].name == VolumeName)
                    return existing[i];
            var go = new GameObject(VolumeName);
            return go.AddComponent<Volume>();
        }

        static Tuning TuningFor(string scene)
        {
            // Dusk village: cool violet ambient with warm lamp accents — bloom keeps
            // lamps/embers glowing, grade warms midtones so pixel art reads cozy.
            var t = new Tuning
            {
                bloomThreshold = 0.82f, bloomIntensity = 0.45f,
                vignette = 0.24f,
                exposure = 0.05f, saturation = 10f, contrast = 4f, temperature = 6f
            };

            if (scene.StartsWith("Interior"))
            {
                // torch-lit rooms: punchier bloom + deeper vignette + warmer
                t.bloomIntensity = 0.65f; t.vignette = 0.3f;
                t.exposure = 0.02f; t.saturation = 6f; t.temperature = 12f;
            }
            else if (scene == "MainMenu" || scene == "Splash")
            {
                t.bloomIntensity = 0.7f; t.vignette = 0.28f;
                t.saturation = 8f; t.temperature = 8f;
            }
            else if (scene == "Cinematic")
            {
                t.bloomIntensity = 0.55f; t.vignette = 0.27f;
                t.saturation = 7f; t.temperature = 5f;
            }
            return t;
        }
    }
}
